# Generated by Django 5.2.7 on 2025-10-30 06:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WishItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('is_public', models.BooleanField(default=False)),
                ('is_starred', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_item_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemSource',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('source_url', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('source_name', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('wish_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='wishlist.wishitem')),
            ],
        ),
        migrations.AddIndex(
            model_name='wishitem',
            index=models.Index(fields=['uuid'], name='idx_item_uuid'),
        ),
        migrations.AddIndex(
            model_name='wishitem',
            index=models.Index(fields=['user', 'is_public'], name='idx_item_is_public'),
        ),
        migrations.AddIndex(
            model_name='wishitem',
            index=models.Index(fields=['user', 'is_starred'], name='idx_item_is_starred'),
        ),
        migrations.AddIndex(
            model_name='itemsource',
            index=models.Index(fields=['wish_item', 'source_url'], name='idx_item_source_item_url'),
        ),
        migrations.AddIndex(
            model_name='itemsource',
            index=models.Index(fields=['uuid'], name='idx_item_source_uuid'),
        ),
        migrations.AddConstraint(
            model_name='itemsource',
            constraint=models.UniqueConstraint(fields=('source_url', 'wish_item'), name='unique_source_per_item'),
        ),
    ]
