# Generated by Django 5.2.7 on 2025-10-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='itemsource',
            index=models.Index(fields=['wish_item', 'source_url'], name='wishlist_it_wish_it_02ddfc_idx'),
        ),
        migrations.AddConstraint(
            model_name='itemsource',
            constraint=models.UniqueConstraint(fields=('source_url', 'wish_item'), name='unique_source_per_item'),
        ),
    ]
