# Generated by Django 5.2.7 on 2025-10-12 06:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_itemsource_wishlist_it_wish_it_02ddfc_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsource',
            name='source_url',
            field=models.TextField(validators=[django.core.validators.URLValidator()]),
        ),
    ]
