# Generated by Django 5.2.8 on 2025-12-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_alter_itemsource_uuid_alter_wishitem_uuid'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='itemsource',
            name='idx_item_source_item_url',
        ),
        migrations.AddField(
            model_name='itemsource',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='itemsource',
            index=models.Index(fields=['wish_item', 'source_url', 'is_primary'], name='idx_item_source_item_url'),
        ),
    ]
