# Generated by Django 5.2.8 on 2025-12-01 09:16

import django.db.models.deletion
from django.db import migrations, models

SQL = r"""
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'wishlist_wishitem' AND column_name = 'image'
  ) THEN
    EXECUTE 'UPDATE wishlist_wishitem SET image = NULL WHERE image = '''';';
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'wishlist_wishitem' AND column_name = 'image_id'
  ) THEN
    EXECUTE 'UPDATE wishlist_wishitem SET image_id = NULL WHERE image_id = '''';';
  END IF;
END$$;
"""

class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_remove_itemsource_idx_item_source_item_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlobImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('sha256_hash', models.CharField(max_length=120, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['sha256_hash'], name='idx_blobimage_sha256hash'), models.Index(fields=['uploaded_at'], name='idx_blobimage_uploaded_at')],
            },
        ),
        migrations.RunSQL(SQL, reverse_sql=migrations.RunSQL.noop),
        migrations.AlterField(
            model_name='wishitem',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wish_item_image', to='wishlist.blobimage'),
        ),
    ]
