# Generated by Django 5.2.9 on 2025-12-22 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0004_blobimage_alter_wishitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blobimage',
            name='url',
            field=models.TextField(null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddIndex(
            model_name='blobimage',
            index=models.Index(fields=['url'], name='idx_blobimage_url'),
        ),
    ]
