# Generated by Django 5.2.7 on 2025-10-12 06:07

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistuser',
            name='bio',
            field=models.TextField(blank=True, verbose_name='bio'),
        ),
        migrations.AddField(
            model_name='wishlistuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/users/profile_images/', verbose_name='profile image'),
        ),
        migrations.AlterField(
            model_name='wishlistuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 200 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=200, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
