# Generated by Django 5.2.7 on 2025-11-05 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishaccount', '0001_initial'),
        ('wishaccount', '0002_wishlistuser_bio_wishlistuser_profile_image_and_more'),
    ]

    operations = [
    ]
