# Generated by Django 5.2.7 on 2025-11-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishaccount', '0003_merge_20251105_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='users/profile/', verbose_name='profile image'),
        ),
    ]
