# Generated by Django 5.2.9 on 2026-01-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishaccount', '0004_alter_wishlistuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistuser',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
    ]
