'''
Django settings for capellawish project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
'''

import json
from pathlib import Path
from datetime import timedelta
import os
import logging.config
from django.core.management.commands.runserver import Command as runserver

def get_secrets(filepath: Path) -> dict:
    # Check whether the secrets.json file exists
    if not filepath.exists():
        return {}

    with filepath.open() as f:
        secrets: dict = json.loads(f.read())
    return secrets

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

SECRETS = get_secrets(os.getenv('SECRETS_FILE', BASE_DIR / 'secrets.json'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = SECRETS.get('SECRET_KEY', os.getenv('SECRET_KEY', None))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

LOGGING_DIRECTORY = os.path.join(BASE_DIR, 'logs')

# Combined with Django's default logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'formatters': {
        'django': {
            '()': 'django.utils.log.ServerFormatter',
            'format': '[{levelname} {asctime}] {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'fileformatter': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'django'
        },
        'file': {
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': '{}/django.log'.format(LOGGING_DIRECTORY),
            'when': 'midnight',
            'interval': 30,
            'backupCount': 10,
            'formatter': 'fileformatter',
        }
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
#         'django.db.backends': {
#             'handlers': ['console'],
#             'level': 'DEBUG',
#             'propagate': False,
#         },
    }
}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',

    'dj_rest_auth',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    'corsheaders',

    'drf_spectacular',
    'drf_spectacular_sidecar',

    'silk',

    'post_office',

    # Apps
    'account',
    'wishlist',
    'list'
]

SITE_ID = 1

MIDDLEWARE = [
    'silk.middleware.SilkyMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = 'capellawish.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request'
            ],
        },
    },
]

WSGI_APPLICATION = 'capellawish.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'HOST': SECRETS.get('DB_HOST', os.getenv('POSTGRES_HOST', 'localhost')),
        'PORT': SECRETS.get('DB_PORT', os.getenv('POSTGRES_PORT', 5432)),
        'NAME': SECRETS.get('DB_NAME', os.getenv('POSTGRES_DB', 'capellawish')),
        'USER': SECRETS.get('DB_USER', os.getenv('POSTGRES_USER', 'capellawish')),
        'PASSWORD': SECRETS.get('DB_PASSWORD', os.getenv('POSTGRES_PASSWORD', '')),
        'TEST': {
            'NAME': SECRETS.get('DB_TEST_NAME', os.getenv('DB_TEST_NAME', 'test_capellawish')),
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        'OPTIONS': {
            'max_similarity': 0.7
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'wishaccount.WishListUser'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly'
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'dj_rest_auth.jwt_auth.JWTCookieAuthentication',
        'dj_rest_auth.jwt_auth.JWTAuthentication',
#         'rest_framework_simplejwt.authentication.JWTAuthentication',
#         'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'CapellaWish API',
    'DESCRIPTION': 'API documentation for the CapellaWish project',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,

    # OTHER SETTINGS
    'SWAGGER_UI_DIST': 'SIDECAR',
    'SWAGGER_UI_FAVICON_HREF': 'SIDECAR',
}


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': '',
    'AUDIENCE': SECRETS.get('SIMPLE_JWT_AUDIENCE', os.getenv('SIMPLE_JWT_AUDIENCE', None)),
    'ISSUER': SECRETS.get('SIMPLE_JWT_ISSUER', os.getenv('SIMPLE_JWT_ISSUER', None)),
    'JSON_ENCODER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    'ON_LOGIN_SUCCESS': 'rest_framework_simplejwt.serializers.default_on_login_success',
    'ON_LOGIN_FAILED': 'rest_framework_simplejwt.serializers.default_on_login_failed',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    # 'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    # 'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    # 'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),

    'TOKEN_OBTAIN_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenObtainPairSerializer',
    'TOKEN_REFRESH_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenRefreshSerializer',
    'TOKEN_VERIFY_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenVerifySerializer',
    'TOKEN_BLACKLIST_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenBlacklistSerializer',
    # 'SLIDING_TOKEN_OBTAIN_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenObtainSlidingSerializer',
    # 'SLIDING_TOKEN_REFRESH_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenRefreshSlidingSerializer',
}


REST_AUTH = {
    'LOGIN_SERIALIZER': 'dj_rest_auth.serializers.LoginSerializer',
    'TOKEN_SERIALIZER': 'dj_rest_auth.serializers.TokenSerializer',
    'JWT_SERIALIZER': 'account.serializers.JWTTokenSerializer',
    'JWT_SERIALIZER_WITH_EXPIRATION': 'account.serializers.JWTTokenWithExpirationSerializer',
    'JWT_TOKEN_CLAIMS_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenObtainPairSerializer',
    'PASSWORD_RESET_SERIALIZER': 'dj_rest_auth.serializers.PasswordResetSerializer',
    'PASSWORD_RESET_CONFIRM_SERIALIZER': 'dj_rest_auth.serializers.PasswordResetConfirmSerializer',

    'REGISTER_PERMISSION_CLASSES': ('rest_framework.permissions.AllowAny',),

    'TOKEN_MODEL': 'rest_framework.authtoken.models.Token',
    'TOKEN_CREATOR': 'dj_rest_auth.utils.default_create_token',

    'PASSWORD_RESET_USE_SITES_DOMAIN': False,
    'OLD_PASSWORD_FIELD_ENABLED': False,
    'LOGOUT_ON_PASSWORD_CHANGE': True,
    'SESSION_LOGIN': False,
    'USE_JWT': True,

    'JWT_AUTH_COOKIE': 'jwt_accesstoken',
    'JWT_AUTH_REFRESH_COOKIE': 'jwt_refreshtoken',
    'JWT_AUTH_REFRESH_COOKIE_PATH': '/',
    'JWT_AUTH_SECURE': True,
    'JWT_AUTH_HTTPONLY': True,
    'JWT_AUTH_SAMESITE': 'Lax',
    'JWT_AUTH_RETURN_EXPIRATION': True,
    'JWT_AUTH_COOKIE_USE_CSRF': False,
    'JWT_AUTH_COOKIE_ENFORCE_CSRF_ON_UNAUTHENTICATED': False,
}

# CSRF Configurations

CSRF_COOKIE_HTTPONLY = True

CSRF_COOKIE_SECURE = True

CSRF_COOKIE_AGE = 314496000 # 1 year

CSRF_COOKIE_DOMAIN = None

CSRF_COOKIE_NAME = 'csrftoken'

CSRF_COOKIE_PATH = '/'

CSRF_COOKIE_SAMESITE = 'Lax'

CSRF_USE_SESSIONS = False

CSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure'

CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'https://localhost:8081'
]

SESSION_COOKIE_SECURE = True

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# CORS Configuration
CORS_ALLOW_ALL_ORIGINS = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'static'

MEDIA_URL = 'media/'

MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Django Silk Configuration

SILKY_AUTHENTICATION = True    # User must be logged in
SILKY_AUTHORISATION = True     # User must have permissions

SILKY_SENSITIVE_KEYS = {'username', 'api', 'token', 'key', 'secret', 'password', 'signature', 'access', 'refresh'}

SILKY_PERMISSIONS = lambda user: user.is_superuser


# DRF Login

LOGIN_URL = '/api/auth/login/'

LOGIN_REDIRECT_URL = '/api/'


# WWW Prepend

PREPEND_WWW = False


# Email Settings

EMAIL_BACKEND = 'post_office.EmailBackend'

EMAIL_HOST = SECRETS.get('EMAIL_HOST', os.getenv('EMAIL_HOST', 'example.org'))

EMAIL_PORT = SECRETS.get('EMAIL_PORT', os.getenv('EMAIL_PORT', 587))

EMAIL_HOST_USER = SECRETS.get('EMAIL_HOST_USER', os.getenv('EMAIL_HOST_USER', 'PlaceholderUser'))

EMAIL_HOST_PASSWORD = SECRETS.get('EMAIL_HOST_PASSWORD', os.getenv('EMAIL_HOST_PASSWORD', 'Placeholder'))

EMAIL_USE_TLS = SECRETS.get('EMAIL_USE_TLS', os.getenv('EMAIL_USE_TLS', False))

DEFAULT_FROM_EMAIL = SECRETS.get('DEFAULT_FROM_EMAIL', os.getenv('DEFAULT_FROM_EMAIL', ''))

EMAIL_REQUIRED = False


# AllAuth Settings

ACCOUNT_ADAPTER = 'account.email.DjangoPostOfficeAccountAdapter'

ACCOUNT_CONFIRM_EMAIL_ON_GET = False

ACCOUNT_EMAIL_CONFIRMATION_HMAC = True

ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3

ACCOUNT_EMAIL_VERIFICATION = SECRETS.get('ACCOUNT_EMAIL_VERIFICATION', os.getenv('ACCOUNT_EMAIL_VERIFICATION', 'none'))

ACCOUNT_EMAIL_VERIFICATION_BY_CODE_ENABLED = False

ACCOUNT_EMAIL_VERIFICATION_BY_CODE_MAX_ATTEMPTS = 3

ACCOUNT_EMAIL_VERIFICATION_BY_CODE_TIMEOUT = 900

ACCOUNT_EMAIL_VERIFICATION_SUPPORTS_CHANGE = False

ACCOUNT_EMAIL_VERIFICATION_SUPPORTS_RESEND = True

ACCOUNT_REAUTHENTICATION_TIMEOUT = 300

ACCOUNT_REAUTHENTICATION_REQUIRED = False

ACCOUNT_AUTHENTICATED_LOGIN_REDIRECTS = True

ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = LOGIN_URL

ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = None

ACCOUNT_LOGOUT_REDIRECT_URL = '/'

ACCOUNT_SIGNUP_REDIRECT_URL = LOGIN_REDIRECT_URL

ACCOUNT_EMAIL_SUBJECT_PREFIX = '[Site] '

ACCOUNT_EMAIL_UNKNOWN_ACCOUNTS = True

ACCOUNT_EMAIL_NOTIFICATIONS = False

ACCOUNT_CHANGE_EMAIL = False

ACCOUNT_EMAIL_MAX_LENGTH = 254

ACCOUNT_MAX_EMAIL_ADDRESSES = None

ACCOUNT_UNIQUE_EMAIL = True

ACCOUNT_RATE_LIMITS = {
    'confirm_email': '10/2m/key'
}

# Only for sending emails
ACCOUNT_SIGNUP_FIELDS = ['username', 'email*', 'password1', 'password2']


# Support email address
SUPPORT_EMAIL = SECRETS.get('SUPPORT_EMAIL', os.getenv('SUPPORT_EMAIL', ''))

# Cache Settings

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    }
}
