# Generated by Django 5.2.7 on 2025-10-30 06:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wishlist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListModel',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lists')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allow_completion_by_other', models.BooleanField(default=False)),
                ('allow_anonymous_completion', models.BooleanField(default=False)),
                ('is_shared', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(blank=True, to='wishlist.wishitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wishitem_list',
                'db_table_comment': 'Lists of wishlist items',
                'ordering': ['user'],
                'indexes': [models.Index(fields=['is_deleted'], name='wishitem_li_is_dele_9f1cfc_idx'), models.Index(fields=['user'], name='wishitem_li_user_id_ac9694_idx'), models.Index(fields=['uuid'], name='wishitem_li_uuid_a0d981_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'title'), name='unique_list_title')],
            },
        ),
    ]
