# Generated by Django 5.2.8 on 2025-12-01 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
        ('wishlist', '0004_blobimage_alter_wishitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listmodel',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_image', to='wishlist.blobimage'),
        ),
    ]
